FROM selenium/standalone-firefox:134.0-20250323

USER root

RUN apt-get update && \
    apt-get install -y nodejs npm && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN mkdir -p /app/allure-results && \
    chown -R seluser:seluser /app && \
    chmod -R 777 /app/allure-results

USER seluser

CMD ["npm", "run", "test:firefox"]